model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7fec4fd64ac0>
  lr: 1
  history_size: 5
  max_iter: 50
  tolerance_grad: 1e-07
  tolerance_change: 1e-09
  line_search_fn: strong_wolfe
  __class__: StationaryOptimizer
  __constructor__: StationaryOptimizer
