model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7f69085866c0>
  lr: 0.003
  betas: (0.9, 0.999, 0.9)
  alpha: 0.1
  scale: 1.0
  eps: 1e-08
  __class__: TAME
  __constructor__: TAME
