model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7f5c727c7e60>
  lr: 0.1
  momentum: 0
  dampening: 0
  weight_decay: 0
  nesterov: false
  maximize: false
  foreach: None
  differentiable: false
  fused: None
  __class__: SGD
  __constructor__: SGD
