model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7f4958877bc0>
  lr: 0.003
  betas: (0.9, 0.99)
  eps: 1e-06
  weight_decay: 0
  amsgrad: false
  foreach: None
  maximize: false
  capturable: false
  differentiable: false
  fused: None
  __class__: Adam
  __constructor__: Adam
