model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7fbe727091c0>
  lr: 0.01
  beta: 0.9
  epsilon: 1e-08
  __class__: FourierPreconditioner
  __constructor__: FourierPreconditioner
