model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7feafe0af140>
  lr: 1
  max_iter: 20
  max_eval: None
  tolerance_grad: 1e-07
  tolerance_change: 1e-09
  history_size: 100
  line_search_fn: None
  __class__: LBFGS
  __constructor__: LBFGS
