model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7fbe4a92fd80>
  lr: 0.1
  betas: (0.9, 0.999, 0.99)
  epsilon: 1e-06
  update_freq: 10
  line_search_freq: 100
  line_search_iters: 10
  line_search_init_lr: 1
  cubic_solve_eps: 1e-08
  max_ls: 5
  max_third_order: 1.0
  h_floor: 1e-08
  t_floor: 1e-12
  __class__: CubicPrecond
  __constructor__: CubicPrecond
