model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7febb21ad8c0>
  lr: 0.1
  history_size: 5
  max_iter: 50
  tolerance_grad: 1e-07
  tolerance_change: 1e-09
  line_search_fn: None
  __class__: StationaryOptimizer
  __constructor__: StationaryOptimizer
