model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7fbe4c6c4580>
  lr: 0.0001
  max_dist: 100000.0
  validate_step: true
  momentum: 0
  dampening: 0
  weight_decay: 0
  nesterov: false
  __class__: DirectionalNewton
  __constructor__: DirectionalNewton
