model: ResNet18
loss_fn: cross_entropy
optimizer:
  params: <generator object Module.parameters at 0x7fbe4ac651c0>
  lr: 0.01
  betas: (0.9, 0.999)
  eps: 1e-08
  __class__: LambertWOptimizer
  __constructor__: LambertWOptimizer
